# Generated by Django 5.1.3 on 2024-11-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0002_alter_foto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
