# Generated by Django 5.1.3 on 2024-11-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0003_alter_foto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fotoCurso',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fotoUser',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
