# Generated by Django 5.1.3 on 2024-11-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0004_curso_fotocurso_usuario_fotouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fotoCurso',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
