# Generated by Django 5.1.3 on 2024-11-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0005_alter_curso_fotocurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fotoCurso',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
    ]
