# Generated by Django 5.1.3 on 2024-11-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0006_alter_curso_fotocurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fotoCurso',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotoUser',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
