# Generated by Django 5.1.3 on 2024-11-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0007_alter_curso_fotocurso_alter_usuario_fotouser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fotoUser',
            new_name='foto',
        ),
    ]
