# Generated by Django 5.1.2 on 2024-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0009_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.IntegerField()),
                ('nome_curso', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
